### ISSUE TITLE
🗺 Add `lazy` property to Route

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#9884]
Don't want to add a new function like `createModuleRoutes` we just want to add `<Route module>` and then ignore all the other things.

## Progress

- [x] Discussion: https://github.com/remix-run/react-router/discussions/9826
- [x] PR: https://github.com/remix-run/react-router/pull/10045
- [x] Original user-land approach PR: https://github.com/remix-run/react-router/pull/9830
- [x] Blog Post PR: https://github.com/remix-run/remix-website/pull/75

**Comment by ryanflorence** [comment]
@markdalgleish get to a happy place and then we'll have a meeting to figure out how much Remix (particularly manifest routes) we want to bring over to React Router.

**Comment by brophdawg11** [comment]
This is released in `react-router-dom@6.9.0-pre.0` if anyone is keeping an eye on this and wants to give it a test spin 😉

**Comment by david-crespo** [comment]
Tried both the `lazy` prop and the non-lazy `Component` prop. Looking good! I could definitely get into a pattern like this for things I don't care about code-splitting.

```ts
import * as SSHKeysPage from './pages/settings/SSHKeysPage'

<Route path="ssh-keys" {...SSHKeysPage } />
```

**Comment by brophdawg11** [comment]
Released in `6.9.0`
